CONFIG_SMP=y
CONFIG_MP_MAX_NUM_CPUS=2
CONFIG_X86_MMU=y
CONFIG_SCHED_CPU_MASK=y
CONFIG_THREAD_NAME=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_PRINTK=y
CONFIG_LOG=n
CONFIG_ASSERT=y
CONFIG_REBOOT=y
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_SRAM_SIZE=65536
